#!/usr/bin/env bash
tail -n 80 stdout.log;
timestamp=`date +%H:%M`;
echo -------------------------------------------$timestamp---------------------------------------------;
while true;do 
timestamp=`date +%H:%M`;
size1=$(stat -c '%s' stdout.log);
sleep 1;
size2=$(stat -c '%s' stdout.log);
if [ $size1 -ne $size2 ];then 
tail -n 80 stdout.log;
echo -------------------------------------------$timestamp---------------------------------------------;
fi;
done
