#!/usr/bin/env python
import os
import numpy as np
import pandas as pd
from ReadPOSCAR import ReadPOSCAR

print("-" * 50)
print("|" + " " * 48 + "|")
print("|" + "Atomic positions from POSCAR".center(48, " ") + "|")
print("|" + "Made by mjhong".center(48, " ") + "|")
print("|" + "v1.0".center(48, " ") + "|")
print("|" + " " * 48 + "|")
print("-" * 50 + "\n\n")

filepath = input("Input POSCAR file path : ")
latticeVectors = np.array(ReadPOSCAR(filepath)[1])
atoms = np.array(ReadPOSCAR(filepath)[2])
positions = np.array(ReadPOSCAR(filepath)[3])

positionsWithAtoms = pd.DataFrame(
    {
        "a": positions[:, 0],
        "b": positions[:, 1],
        "c": positions[:, 2],
        "atom": [atoms[i] + str(i + 1) for i in range(len(atoms))],
    }
)

print(positionsWithAtoms)
cwd = os.getcwd()
positionsWithAtoms.to_csv(cwd + "/" + filepath + ".csv")
