#!/usr/bin/env python
import matplotlib.pyplot as plt
import sys


filename = sys.argv[1]
with open(filename, "rb") as file:
    image = plt.imread(file)

plt.figure(dpi=600)
plt.gca().spines['left'].set_visible(False)
plt.gca().spines['right'].set_visible(False)
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['bottom'].set_visible(False)
plt.imshow(image)
plt.xticks([])
plt.yticks([])
plt.show()
