#!/usr/bin/env python
from rich.console import Console
from rich.table import Table
import os

os.system("pestat | awk '{print $1,$2,$3,$4,$5,$10}' > /home/hmj0327/temp.txt")
table = Table(title="Node configuration")

table.add_column("Node", justify="right", no_wrap=True)
table.add_column("Type",)
table.add_column("Status")
table.add_column("Using cores", justify='center')
table.add_column("Total cores", justify='center')
table.add_column("User")
table.add_column("Owner")
# table.add_column


with open("/home/hmj0327/temp.txt", "r") as f:
    lines = f.readlines()
node_owner = (
    ["Shared"] * 46 + ["choah"] * 4 + ["ingrid1226"] * 4 + ["hmj0327"] * 4 + ["ghlwjd0403"] * 4 + ["kjy0825"] * 3 +
    ["ksi97"] * 3 + ["hsj1021"] * 4 + ["ju9407"] * 4 + ["singsingi"] * 3 + ["poong"] * 3 + ["csj356093"] * 3 + 
    ["juwondi"] * 2 + ["taowei0817"] * 3 + ["mka1203"] * 3 + ["jungsdao"] * 1 + ["soyong"] * 1 + 
    ["Group 1"] * 3 + ["Group 2"] * 3 + ["Group 3"] * 3
)
len(node_owner)

for i, line in enumerate(lines[2:]):
    line_list = line.split()
    if len(line_list) == 5:
        line_list.append("None")
    line_list.append(node_owner[i])
    if line_list[2] == "idle":
        line_list = ["[bold green]" + line_list[i] for i in range(len(line_list))]
    elif line_list[2] == "down*" or line_list[2] == "comp*":
        line_list = ["[bold red]" + line_list[i] for i in range(len(line_list))]
    if line_list[5] == "hmj0327":
        line_list = ["[bold blue]" + line_list[i] for i in range(len(line_list))]
    table.add_row(*line_list)


console = Console()
console.print(table)
