#!/usr/bin/env python
import json
import argparse
import os


parser = argparse.ArgumentParser(description="add energy")
parser.add_argument("-rm", default=None)
parser.add_argument("-s", default=None, type=str)
parser.add_argument("-E", default=None, type=float)
parser.add_argument("-o", action="store_const", const=True)
args = parser.parse_args()

if "energies.json" not in os.listdir():
    with open("energies.json", "w") as file:
        file.write("[]")

with open("energies.json", "r") as file:
    energies = json.load(file)
system_names = [list(item.values())[0] for item in energies]
if args.rm is None:
    if args.s not in system_names:
        energies.append({"system": args.s, "E": args.E})
    else:
        existing_index = system_names.index(args.s)
        energies[existing_index] = {"system": args.s, "E": args.E}
else:
    existing_index = system_names.index(args.rm)
    energies.remove(energies[existing_index])

if args.o:
    from pandas import DataFrame as df

    print(df(energies))

with open("energies.json", "w") as file:
    json.dump(energies, file, separators=(",", ":"))
