#!/usr/bin/env python

from bader_view import mkCharge
from ReadPOSCAR import ReadPOSCAR
import sys
import numpy as np
import pandas as pd

argv = sys.argv
if len(argv) == 1:
    print("Error : Input filpath")
else:
    paths = argv[1:]
    positions = np.array([np.array(ReadPOSCAR(path + "POSCAR")[3]) for path in paths])
    print(type(positions[1]))
    charges = [mkCharge(path) for path in paths]
    charges_DF = pd.DataFrame({})
    i = 0
    for path in paths:
        charges_DF = pd.concat(
            [
                charges_DF,
                pd.DataFrame({"Atom({})".format(path): list(charges[i].keys())}),
            ],
            axis=1,
        )

        charges_DF = pd.concat(
            [
                charges_DF,
                pd.DataFrame(
                    {"a": list(map(lambda x: round(x, 2), positions[i][:, 0]))}
                ),
            ],
            axis=1,
        )
        charges_DF = pd.concat(
            [
                charges_DF,
                pd.DataFrame(
                    {"b": list(map(lambda x: round(x, 2), positions[i][:, 1]))}
                ),
            ],
            axis=1,
        )

        charges_DF = pd.concat(
            [
                charges_DF,
                pd.DataFrame(
                    {"c": list(map(lambda x: round(x, 2), positions[i][:, 2]))}
                ),
            ],
            axis=1,
        )
        charges_DF = pd.concat(
            [charges_DF, pd.DataFrame({"charge": list(charges[i].values())})], axis=1
        )
        i += 1
print(charges_DF)
charges_DF.to_csv("summedBader.csv")
