#!/usr/bin/env python
import os
import math
import re
import numpy as np
from ReadPOSCAR import ReadPOSCAR


class bcolors:
    HEADER = "\033[95m"
    OKBLUE = "\033[94m"
    CYAN = "\033[96m"
    OKGREEN = "\033[92m"
    WARNING = "\033[93m"
    FAIL = "\033[91m"
    ENDC = "\033[0m"
    BOLD = "\033[1m"
    UNDERLINE = "\033[4m"


print("-" * 85)
print("|" + " " * 83 + "|")
print(
    "|"
    + " ____   ___  ____   ____    _    ____    _____       ____  ____  ___ __  __ ".center(
        83, " "
    )
    + "|"
)
print(
    "|"
    + "|  _ \ / _ \/ ___| / ___|  / \  |  _ \  |_   _|__   |  _ \|  _ \|_ _|  \/  |".center(
        83, " "
    )
    + "|"
)
print(
    "|"
    + "| |_) | | | \___ \| |     / _ \ | |_) |   | |/ _ \  | |_) | |_) || || |\/| |".center(
        83, " "
    )
    + "|"
)
print(
    "|"
    + "|  __/| |_| |___) | |___ / ___ \|  _ <    | | (_) | |  __/|  _ < | || |  | |".center(
        83, " "
    )
    + "|"
)
print(
    "|"
    + "|_|    \___/|____/ \____/_/   \_\_| \_\   |_|\___/  |_|   |_| \_\___|_|  |_|".center(
        83, " "
    )
    + "|"
)
print("|" + " " * 83 + "|")
print("|" + "Automatic POSCAR tranformation to prim.json".center(83, " ") + "|")
print("|" + "Made by mjhong".center(83, " ") + "|")
print("|" + "v1.0".center(83, " ") + "|")
print("|" + " " * 83 + "|")
print("-" * 85 + "\n\n")
filepath = input("Input POSCAR file path to transform : ")
latticeVectors = ReadPOSCAR(filepath)[1]
atoms = ReadPOSCAR(filepath)[2]
positions = ReadPOSCAR(filepath)[3]

prim = open("prim.json", "w")
prim.write("{\n")

prim.write('"basis" : [\n')
count = 0
for atom in atoms:
    prim.write("{\n")
    prim.write('"coordinate" : {},\n'.format(list(positions[count])))
    prim.write('"occupant_dof" : ["{}"]\n'.format(atoms[count]))
    count += 1
    prim.write("},\n")
prim.write("],\n")

prim.write('"coordinate_mode" : "Fractional",\n')
prim.write('"description" : "{}",\n'.format(ReadPOSCAR(filepath)[0]))
prim.write('"lattice_vectors" : [\n')
prim.write("{},\n".format(list(latticeVectors[0])))
prim.write("{},\n".format(list(latticeVectors[1])))
prim.write("{}\n".format(list(latticeVectors[2])))
prim.write("],\n")
prim.write('"title" : "{}"\n'.format(ReadPOSCAR(filepath)[0]))
prim.write("}")
prim.close()

prim_written = open("prim.json", "r")
print("\n[prim.json]")
for line in prim_written.readlines():
    print(line, end="")

print(bcolors.CYAN + "\n\nTransformation complete!" + bcolors.ENDC)
print(
    bcolors.CYAN
    + bcolors.BOLD
    + "Make sure to modify degree of freedom manually!"
    + bcolors.ENDC
)
